export var list = [
    {
        year:2018,
        list:[
            {
                name:'奖学金名称',
                revenue:100000,
                org:'院办学生处1院办学生处1院办学生处1',
                date:'2018.12.12',
                revenueType:'1'
            },
            {
                name:'助学金名称',
                revenue:200000,
                org:'院办学生处1院办学生处1院办学生处1',
                date:'2018.12.12',
                revenueType:'2'
            },
            {
                name:'补助奖金',
                revenue:300000,
                org:'院办学生处1院办学生处1院办学生处1',
                date:'2018.12.12',
                revenueType:'3'
            },
            {
                name:'三助奖金',
                revenue:400000,
                org:'院办学生处1院办学生处1院办学生处1',
                date:'2018.12.12',
                revenueType:'4'
            },
            {
                name:'奖金1',
                revenue:500000,
                org:'院办学生处1院办学生处1院办学生处1',
                date:'2018.12.12',
                revenueType:'1'
            },
            {
                name:'奖金1',
                revenue:600000,
                org:'院办学生处1院办学生处1院办学生处1',
                date:'2018.12.12',
                revenueType:'2'
            },
            {
                name:'奖金1',
                revenue:700000,
                org:'院办学生处1院办学生处1院办学生处1',
                date:'2018.12.12',
                revenueType:'3'
            },
            {
                name:'奖金1',
                revenue:800000,
                org:'院办学生处1院办学生处1院办学生处1',
                date:'2018.12.12',
                revenueType:'4'
            },
        ]
        
    },
    {
        year:2017,
        list:[
            {
                name:'奖金1',
                revenue:100000,
                org:'院办学生处1院办学生处1院办学生处1',
                date:'2018.12.12',
                revenueType:'1'
            },
            {
                name:'奖金1',
                revenue:200000,
                org:'院办学生处1院办学生处1院办学生处1',
                date:'2018.12.12',
                revenueType:'2'
            },
            {
                name:'奖金1',
                revenue:300000,
                org:'院办学生处1院办学生处1院办学生处1',
                date:'2018.12.12',
                revenueType:'3'
            },
            {
                name:'奖金1',
                revenue:400000,
                org:'院办学生处1院办学生处1院办学生处1',
                date:'2018.12.12',
                revenueType:'4'
            },
            {
                name:'奖金1',
                revenue:500000,
                org:'院办学生处1院办学生处1院办学生处1',
                date:'2018.12.12',
                revenueType:'1'
            },
            {
                name:'奖金1',
                revenue:600000,
                org:'院办学生处1院办学生处1院办学生处1',
                date:'2018.12.12',
                revenueType:'2'
            },
            {
                name:'奖金1',
                revenue:700000,
                org:'院办学生处1院办学生处1院办学生处1',
                date:'2018.12.12',
                revenueType:'3'
            },
            {
                name:'奖金1',
                revenue:800000,
                org:'院办学生处1院办学生处1院办学生处1',
                date:'2018.12.12',
                revenueType:'4'
            },
        ]
        
    },
]