export var data1 =  [
    {
        time:'2017-2018第三学期',
        nodes:[
            {
                id:11,
                score:98.76,
                name:'美术选讲',
                type:'a',
                score1:92,
                score2:93
            },
            {
                id:12,
                score:87,
                name:'历史选讲',
                type:'b',
                score1:67,
                score2:72
            },
            {
                id:13,
                score:76.5,
                name:'政治选讲',
                type:'c',
                score1:51,
                score2:68
            },
            {
                id:14,
                score:76.54,
                name:'外语选讲',
                type:'d',
                score1:51,
                score2:68
            }
        ]
    },
    {
        time:'2017-2018第四学期',
        nodes:[
            {
                id:21,
                score:98.76,
                name:'几何选讲',
                type:'a',
                score1:12,
                score2:23
            },
            {
                id:22,
                score:87.76,
                name:'代数选讲',
                type:'b',
                score1:56,
                score2:78
            },
            {
                id:23,
                score:76.54,
                name:'政治选讲',
                type:'c',
                score1:51,
                score2:68
            },
            {
                id:24,
                score:76.54,
                name:'外语选讲',
                type:'d',
                score1:51,
                score2:68
            }
        ]
    }
]

export var data2 = [
    {
        time:'2016-2017第一学期',
        nodes:[
            {
                id:11,
                name:"2017-2018第一学期",
                score:123.45
            },
            {
                id:12,
                name:"2017-2018第二学期",
                score:234.56
            },
            {
                id:13,
                name:"2017-2018第三学期",
                score:99.99
            },
            {
                id:14,
                name:"2017-2018第四学期",
                score:89.09
            }
        ]
    },
    {
        time:'2016-2017第二学期',
        nodes:[
            {
                id:21,
                name:"2016-2017第一学期",
                score:78.90
            },
            {
                id:22,
                name:"2016-2017第二学期",
                score:67.89
            },
            {
                id:23,
                name:"2016-2017第三学期",
                score:45.67
            },
            {
                id:24,
                name:"2016-2017第四学期",
                score:45.67
            }
        ]
    }
]